/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ResourceListerExpansion allows custom methods to be added to
// ResourceLister.
type ResourceListerExpansion interface{}

// ResourceNamespaceListerExpansion allows custom methods to be added to
// ResourceNamespaceLister.
type ResourceNamespaceListerExpansion interface{}

// StageListerExpansion allows custom methods to be added to
// StageLister.
type StageListerExpansion interface{}

// StageNamespaceListerExpansion allows custom methods to be added to
// StageNamespaceLister.
type StageNamespaceListerExpansion interface{}

// StageTemplateListerExpansion allows custom methods to be added to
// StageTemplateLister.
type StageTemplateListerExpansion interface{}

// StageTemplateNamespaceListerExpansion allows custom methods to be added to
// StageTemplateNamespaceLister.
type StageTemplateNamespaceListerExpansion interface{}

// WorkflowListerExpansion allows custom methods to be added to
// WorkflowLister.
type WorkflowListerExpansion interface{}

// WorkflowNamespaceListerExpansion allows custom methods to be added to
// WorkflowNamespaceLister.
type WorkflowNamespaceListerExpansion interface{}

// WorkflowParamListerExpansion allows custom methods to be added to
// WorkflowParamLister.
type WorkflowParamListerExpansion interface{}

// WorkflowParamNamespaceListerExpansion allows custom methods to be added to
// WorkflowParamNamespaceLister.
type WorkflowParamNamespaceListerExpansion interface{}

// WorkflowRunListerExpansion allows custom methods to be added to
// WorkflowRunLister.
type WorkflowRunListerExpansion interface{}

// WorkflowRunNamespaceListerExpansion allows custom methods to be added to
// WorkflowRunNamespaceLister.
type WorkflowRunNamespaceListerExpansion interface{}

// WorkflowTriggerListerExpansion allows custom methods to be added to
// WorkflowTriggerLister.
type WorkflowTriggerListerExpansion interface{}

// WorkflowTriggerNamespaceListerExpansion allows custom methods to be added to
// WorkflowTriggerNamespaceLister.
type WorkflowTriggerNamespaceListerExpansion interface{}
