run:
  # concurrency: 2
  deadline: 5m
  skip-dirs:
    - pkg/k8s/
    - tools/generator

# all available settings of specific linters
linters-settings:
  misspell:
    ignore-words:
      - noteable

linters:
  enable:
    - golint
    - goconst
    - gofmt
    - goimports
    - misspell

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
