run:
  # concurrency: 2
  deadline: 5m
  skip-dirs:
    - pkg/k8s/
    - tools/generator

linters:
  enable:
    - golint
    - goconst
    - gofmt
    - goimports
    - misspell

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - noteable # gitlab parameters
      - cancelled # some of them should be fix after check

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
