- apiVersion: cyclone.dev/v1alpha1
  kind: Stage
  metadata:
    name: build
    labels:
      stage.cyclone.dev/template: "true"
      cyclone.dev/builtin: "true"
      cyclone.dev/scene: cicd
      stage.cyclone.dev/template-kind: build
    annotations:
      cyclone.dev/description: >
        Build source code
  spec:
    pod:
      inputs:
        arguments:
        - name: image
          description: Image to run this stage, for example, 'golang:1.10-alpine3.8'
        - name: cmd
          description: Commmands to run, multiple commands supported here, commands will be run as '/bin/sh -c {{{ cmd }}}'
        - name: output-artifact-path
          description: Path to the output artifacts, for example, '/workspace/target/app.war'
        resources:
        - type: Git
          path: /workspace
      outputs:
        artifacts:
        - name: bin
          path: "{{ output-artifact-path }}"
      spec:
        containers:
        - image: "{{ image }}"
          command:
          - /bin/sh
          - -e
          - -c
          - "{{{ cmd }}}"
- apiVersion: cyclone.dev/v1alpha1
  kind: Stage
  metadata:
    name: golang-build
    labels:
      stage.cyclone.dev/template: "true"
      cyclone.dev/builtin: "true"
      cyclone.dev/scene: cicd
      stage.cyclone.dev/template-kind: build
    annotations:
      cyclone.dev/description: >
        Build Golang source code
  spec:
    pod:
      inputs:
        arguments:
        - name: image
          value: golang:1.10-alpine3.8
          description: Image to run this stage, for example, 'golang:1.10-alpine3.8'
        - name: cmd
          value: >-
            go build -o /go/bin/app <main-entrypoint-path>
          description: Commmands to run, multiple commands supported here, commands will be run as '/bin/sh -c {{{ cmd }}}'
        - name: output-artifact-path
          value: /go/bin/app
          description: Path to the output artifacts, for example, '/go/bin/app'
        resources:
        - type: Git
          path: /go/src
      outputs:
        artifacts:
        - name: bin
          path: "{{ output-artifact-path }}"
      spec:
        containers:
        - image: "{{ image }}"
          command:
          - /bin/sh
          - -e
          - -c
          - "{{{ cmd }}}"
- apiVersion: cyclone.dev/v1alpha1
  kind: Stage
  metadata:
    name: maven-build
    labels:
      stage.cyclone.dev/template: "true"
      cyclone.dev/builtin: "true"
      cyclone.dev/scene: cicd
      stage.cyclone.dev/template-kind: build
    annotations:
      cyclone.dev/description: >
        Build Java source code with Maven
  spec:
    pod:
      inputs:
        arguments:
        - name: image
          value: maven:3.5.3-jdk-8-alpine
          description: Image to run this stage, for example, 'maven:3.5.3-jdk-8-alpine'
        - name: cmd
          value: >-
            mvn clean package -Dmaven.test.skip
          description: Commmands to run, multiple commands supported here, commands will be run as '/bin/sh -c {{{ cmd }}}'
        - name: output-artifact-path
          value: /workspace/target/<app>.jar
          description: Path to the output artifacts, for example, '/workspace/target/<app>.jar'
        resources:
        - type: Git
          path: /workspace
      outputs:
        artifacts:
        - name: jar
          path: "{{ output-artifact-path }}"
      spec:
        containers:
        - image: "{{ image }}"
          workingDir: /workspace
          command:
          - /bin/sh
          - -e
          - -c
          - "{{{ cmd }}}"
- apiVersion: cyclone.dev/v1alpha1
  kind: Stage
  metadata:
    name: gradle-build
    labels:
      stage.cyclone.dev/template: "true"
      cyclone.dev/builtin: "true"
      cyclone.dev/scene: cicd
      stage.cyclone.dev/template-kind: build
    annotations:
      cyclone.dev/description: >
        Build Java source code with Gradle
  spec:
    pod:
      inputs:
        arguments:
        - name: image
          value: gradle:5.5.1
          description: Image to run this stage, for example, 'gradle:5.5.1'
        - name: cmd
          value: >-
            gradle build -x test
          description: Commmands to run, multiple commands supported here, commands will be run as '/bin/sh -c {{{ cmd }}}'
        - name: output-artifact-path
          value: /workspace/build/<app>.jar
          description: Path to the output artifacts, for example, '/workspace/build/<app>.jar'
        resources:
        - type: Git
          path: /workspace
      outputs:
        artifacts:
        - name: jar
          path: "{{ output-artifact-path }}"
      spec:
        containers:
        - image: "{{ image }}"
          workingDir: /workspace
          command:
          - /bin/sh
          - -e
          - -c
          - "{{{ cmd }}}"
