- apiVersion: cyclone.dev/v1alpha1
  kind: Stage
  metadata:
    name: cd-template
    labels:
      stage.cyclone.dev/template: "true"
      cyclone.dev/builtin: "true"
      cyclone.dev/scene: cicd
      stage.cyclone.dev/template-kind: cd
    annotations:
      cyclone.dev/description: >
        Continuous deployment
  spec:
    pod:
      inputs:
        arguments:
        - name: image
          value: k8sdevops/cyclone-cicd-cd:v0.9.5
          description: Image to run this stage, for example, 'k8sdevops/cyclone-cicd-cd:v0.9.5'
        - name: config
          value: >-
            {
              "deployment": {
                "type": "deployment",
                "namespace": "default",
                "name": "app-deployment"
              },
              "images": [
                {
                  "container": "app",
                  "image": "nginx:1.15-alpine"
                }
              ]
            }
          description: JSON to express the CD task, including which deployment, and what containers, images to update.
      spec:
        containers:
        - image: "{{ image }}"
          env:
          - name: _CONFIG_
            value: "{{{ config }}}"