- apiVersion: cyclone.io/v1alpha1
  kind: Stage
  metadata:
    name: image-build-template
    labels:
      cyclone.io/stage-template: "true"
      cyclone.io/builtin: "true"
      cyclone.io/scene: cicd
      cyclone.io/template-kind: image-build
    annotations:
      cyclone.io/description: >
        Build docker image with Dockerfile and build context
  spec:
    pod:
      inputs:
        arguments:
        - name: registry
        - name: repository
        - name: tag
        - name: build-context
          value: .
        - name: dockerfile-path
          value: ./Dockerfile
        - name: image
          value: docker:18.03.1-ce-dind
        - name: cmd
          value: >-
            while [ ! -S /var/run/docker.sock ]; do sleep 1; done;
            docker build -f {{ dockerfile-path }} -t {{ registry }}/{{ repository }}:{{ tag }} {{ build-context }}
        resources:
        - name: code
          path: /workspace
      outputs:
        resources:
        - name: image
      spec:
        containers:
        - image: "{{ image }}"
          workingDir: /workspace
          command:
          - /bin/sh
          - -e
          - -c
          - "{{ cmd }}"