apiVersion: cyclone.io/v1alpha1
kind: Resource
metadata:
  name: test-git
spec:
  type: Git
  persistent: false
  pullPolicy: Always
  parameters:
  - name: GIT_URL
    value: http://192.168.21.100:10081/root/test.git
  - name: GIT_REVISION
    value: master

---

apiVersion: cyclone.io/v1alpha1
kind: Resource
metadata:
  name: docker-image
spec:
  type: Image
  parameters:
  - name: IMAGE
    value: test.caicloudprivatetest.com/release/workflow-test:v0.1
  - name: IMAGE_FILE
    value: image.tar

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: unit-test-stage
spec:
  pod:
    inputs:
      resources:
      - name: test-git
        path: /go/src/root
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/golang:1.10-alpine3.8
        command:
        - /bin/sh
        - -c
        - "ls -al /go/src/root/test && go test root/test"

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: echo-stage
spec:
  pod:
    inputs:
      arguments:
      - name: message
      - name: image
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/{{ image }}
        command:
        - echo
        - "{{ message }}"

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: build-stage
spec:
  pod:
    inputs:
      resources:
      - name: test-git
        path: /go/src/root
    outputs:
      artifacts:
      - name: app
        path: /go/bin/app
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/golang:1.10-alpine3.8
        command:
        - /bin/sh
        - -c
        - "ls -al /go/src/root/test && go build -o /go/bin/app root/test && /go/bin/app"

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: image-build-stage
spec:
  pod:
    inputs:
      resources:
      - name: test-git
        path: /workspace
      artifacts:
      - name: binary
        path: /workspace/app
    outputs:
      resources:
      - name: docker-image
        path: /workspace/image.tar
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/docker:1.13.1-dind
        command:
        - /bin/sh
        - -c
        - >-
          ls -al /workspace &&
          /workspace/app &&
          docker build -f /workspace/test/Dockerfile -t test.caicloudprivatetest.com/release/workflow-test:v0.1 /workspace/test &&
          docker save -o /workspace/image.tar test.caicloudprivatetest.com/release/workflow-test:v0.1 &&
          ls -al /workspace/image.tar
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker-sock-volume

---

apiVersion: cyclone.io/v1alpha1
kind: Workflow
metadata:
  name: ci-workflow
spec:
  stages:
  - name: unit-test-stage
  - name: build-stage
    depends:
    - unit-test-stage
  - name: image-build-stage
    depends:
    - build-stage
    artifacts:
    - name: binary
      source: build-stage/app
  - name: echo-stage

---

apiVersion: cyclone.io/v1alpha1
kind: WorkflowRun
metadata:
  name: ci-workflowrun
spec:
  workflowRef:
    kind: workflow.cyclone.io
    name: ci-workflow
  timeout: 5h
  stages:
  - name: echo-stage
    parameters:
    - name: message
      value: Hello, World~
    - name: image
      value: golang:1.10-alpine3.8