apiVersion: v1
kind: Secret
metadata:
  name: cyclone-secrets
type: Opaque
data:
  config.json: ewoJImF1dGhzIjogewoJCSJ0ZXN0LmNhaWNsb3VkcHJpdmF0ZXRlc3QuY29tIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlVIZGtNVEl6TkRVMiIKCQl9Cgl9Cn0K