apiVersion: cyclone.io/v1alpha1
kind: Resource
metadata:
  name: test-git
spec:
  type: Git
  parameters:
  - name: GIT_URL
    value: http://192.168.21.100:10081/root/test.git
  - name: GIT_REVISION
    value: master

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: simple-unit-test
spec:
  pod:
    inputs:
      resources:
      - name: test-git
        path: /go/src/root
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/golang:1.10-alpine3.8
        command:
        - /bin/sh
        - -c
        - "ls -al /go/src/root/test && go test root/test"

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: simple-echo
spec:
  pod:
    inputs:
      arguments:
      - name: message
      - name: image
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/{{ image }}
        command:
        - echo
        - "{{ message }}"

---

apiVersion: cyclone.io/v1alpha1
kind: Stage
metadata:
  name: simple-build
spec:
  pod:
    inputs:
      resources:
      - name: test-git
        path: /go/src/root
    spec:
      containers:
      - name: main
        image: test.caicloudprivatetest.com/release/golang:1.10-alpine3.8
        command:
        - /bin/sh
        - -c
        - "ls -al /go/src/root/test && go build -o /go/bin/app root/test && /go/bin/app"

---

apiVersion: cyclone.io/v1alpha1
kind: Workflow
metadata:
  name: simple-workflow
spec:
  stages:
  - name: simple-unit-test
  - name: simple-build
    depends:
    - simple-unit-test
  - name: simple-echo

---

apiVersion: cyclone.io/v1alpha1
kind: WorkflowRun
metadata:
  name: simple-workflowrun
spec:
  workflowRef:
    kind: workflow.cyclone.io
    name: simple-workflow
  timeout: 1h
  stages:
  - name: simple-echo
    parameters:
    - name: message
      value: Hello, World~
    - name: image
      value: golang:1.10-alpine3.8