apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resources.cyclone.io
spec:
  group: cyclone.io
  names:
    kind: Resource
    plural: resources
    singular: resource
    shortNames:
    - rsc
  scope: Namespaced
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stages.cyclone.io
spec:
  group: cyclone.io
  names:
    kind: Stage
    plural: stages
    singular: stage
    shortNames:
    - stg
  scope: Namespaced
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.cyclone.io
spec:
  group: cyclone.io
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
    shortNames:
    - wf
  scope: Namespaced
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflowruns.cyclone.io
spec:
  group: cyclone.io
  names:
    kind: WorkflowRun
    plural: workflowruns
    singular: workflowrun
    shortNames:
    - wfr
  scope: Namespaced
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflowtriggers.cyclone.io
spec:
  group: cyclone.io
  names:
    kind: WorkflowTrigger
    plural: workflowtriggers
    singular: workflowtrigger
    shortNames:
    - wft
  scope: Namespaced
  version: v1alpha1