apiVersion: v1
kind: Service
metadata:
  labels:
    name: cyclone-server
  name: cyclone-server
  namespace: cyclone
spec:
  ports:
  - name: http
    port: 7099
    protocol: TCP
    nodePort: 30010
  selector:
    name: cyclone-server
  sessionAffinity: None
  type: NodePort
  