/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/caicloud/cyclone/pkg/apis/cyclone/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCycloneResources implements CycloneResourceInterface
type FakeCycloneResources struct {
	Fake *FakeCycloneV1alpha1
	ns   string
}

var cycloneresourcesResource = schema.GroupVersionResource{Group: "cyclone.caicloud.io", Version: "v1alpha1", Resource: "cycloneresources"}

var cycloneresourcesKind = schema.GroupVersionKind{Group: "cyclone.caicloud.io", Version: "v1alpha1", Kind: "CycloneResource"}

// Get takes name of the cycloneResource, and returns the corresponding cycloneResource object, and an error if there is any.
func (c *FakeCycloneResources) Get(name string, options v1.GetOptions) (result *v1alpha1.CycloneResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cycloneresourcesResource, c.ns, name), &v1alpha1.CycloneResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CycloneResource), err
}

// List takes label and field selectors, and returns the list of CycloneResources that match those selectors.
func (c *FakeCycloneResources) List(opts v1.ListOptions) (result *v1alpha1.CycloneResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cycloneresourcesResource, cycloneresourcesKind, c.ns, opts), &v1alpha1.CycloneResourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CycloneResourceList{}
	for _, item := range obj.(*v1alpha1.CycloneResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cycloneResources.
func (c *FakeCycloneResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cycloneresourcesResource, c.ns, opts))

}

// Create takes the representation of a cycloneResource and creates it.  Returns the server's representation of the cycloneResource, and an error, if there is any.
func (c *FakeCycloneResources) Create(cycloneResource *v1alpha1.CycloneResource) (result *v1alpha1.CycloneResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cycloneresourcesResource, c.ns, cycloneResource), &v1alpha1.CycloneResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CycloneResource), err
}

// Update takes the representation of a cycloneResource and updates it. Returns the server's representation of the cycloneResource, and an error, if there is any.
func (c *FakeCycloneResources) Update(cycloneResource *v1alpha1.CycloneResource) (result *v1alpha1.CycloneResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cycloneresourcesResource, c.ns, cycloneResource), &v1alpha1.CycloneResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CycloneResource), err
}

// Delete takes name of the cycloneResource and deletes it. Returns an error if one occurs.
func (c *FakeCycloneResources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cycloneresourcesResource, c.ns, name), &v1alpha1.CycloneResource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCycloneResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cycloneresourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CycloneResourceList{})
	return err
}

// Patch applies the patch and returns the patched cycloneResource.
func (c *FakeCycloneResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CycloneResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cycloneresourcesResource, c.ns, name, data, subresources...), &v1alpha1.CycloneResource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CycloneResource), err
}
