/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/caicloud/cyclone/pkg/apis/cyclone/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStageTemplates implements StageTemplateInterface
type FakeStageTemplates struct {
	Fake *FakeCycloneV1alpha1
	ns   string
}

var stagetemplatesResource = schema.GroupVersionResource{Group: "cyclone.caicloud.io", Version: "v1alpha1", Resource: "stagetemplates"}

var stagetemplatesKind = schema.GroupVersionKind{Group: "cyclone.caicloud.io", Version: "v1alpha1", Kind: "StageTemplate"}

// Get takes name of the stageTemplate, and returns the corresponding stageTemplate object, and an error if there is any.
func (c *FakeStageTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.StageTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(stagetemplatesResource, c.ns, name), &v1alpha1.StageTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StageTemplate), err
}

// List takes label and field selectors, and returns the list of StageTemplates that match those selectors.
func (c *FakeStageTemplates) List(opts v1.ListOptions) (result *v1alpha1.StageTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(stagetemplatesResource, stagetemplatesKind, c.ns, opts), &v1alpha1.StageTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StageTemplateList{}
	for _, item := range obj.(*v1alpha1.StageTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested stageTemplates.
func (c *FakeStageTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(stagetemplatesResource, c.ns, opts))

}

// Create takes the representation of a stageTemplate and creates it.  Returns the server's representation of the stageTemplate, and an error, if there is any.
func (c *FakeStageTemplates) Create(stageTemplate *v1alpha1.StageTemplate) (result *v1alpha1.StageTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(stagetemplatesResource, c.ns, stageTemplate), &v1alpha1.StageTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StageTemplate), err
}

// Update takes the representation of a stageTemplate and updates it. Returns the server's representation of the stageTemplate, and an error, if there is any.
func (c *FakeStageTemplates) Update(stageTemplate *v1alpha1.StageTemplate) (result *v1alpha1.StageTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(stagetemplatesResource, c.ns, stageTemplate), &v1alpha1.StageTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StageTemplate), err
}

// Delete takes name of the stageTemplate and deletes it. Returns an error if one occurs.
func (c *FakeStageTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(stagetemplatesResource, c.ns, name), &v1alpha1.StageTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStageTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(stagetemplatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.StageTemplateList{})
	return err
}

// Patch applies the patch and returns the patched stageTemplate.
func (c *FakeStageTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StageTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(stagetemplatesResource, c.ns, name, data, subresources...), &v1alpha1.StageTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StageTemplate), err
}
