/*
Copyright 2019 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/caicloud/cyclone/pkg/apis/cyclone/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkflowParams implements WorkflowParamInterface
type FakeWorkflowParams struct {
	Fake *FakeCycloneV1alpha1
	ns   string
}

var workflowparamsResource = schema.GroupVersionResource{Group: "cyclone.io", Version: "v1alpha1", Resource: "workflowparams"}

var workflowparamsKind = schema.GroupVersionKind{Group: "cyclone.io", Version: "v1alpha1", Kind: "WorkflowParam"}

// Get takes name of the workflowParam, and returns the corresponding workflowParam object, and an error if there is any.
func (c *FakeWorkflowParams) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkflowParam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workflowparamsResource, c.ns, name), &v1alpha1.WorkflowParam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowParam), err
}

// List takes label and field selectors, and returns the list of WorkflowParams that match those selectors.
func (c *FakeWorkflowParams) List(opts v1.ListOptions) (result *v1alpha1.WorkflowParamList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workflowparamsResource, workflowparamsKind, c.ns, opts), &v1alpha1.WorkflowParamList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkflowParamList{}
	for _, item := range obj.(*v1alpha1.WorkflowParamList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workflowParams.
func (c *FakeWorkflowParams) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workflowparamsResource, c.ns, opts))

}

// Create takes the representation of a workflowParam and creates it.  Returns the server's representation of the workflowParam, and an error, if there is any.
func (c *FakeWorkflowParams) Create(workflowParam *v1alpha1.WorkflowParam) (result *v1alpha1.WorkflowParam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workflowparamsResource, c.ns, workflowParam), &v1alpha1.WorkflowParam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowParam), err
}

// Update takes the representation of a workflowParam and updates it. Returns the server's representation of the workflowParam, and an error, if there is any.
func (c *FakeWorkflowParams) Update(workflowParam *v1alpha1.WorkflowParam) (result *v1alpha1.WorkflowParam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workflowparamsResource, c.ns, workflowParam), &v1alpha1.WorkflowParam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowParam), err
}

// Delete takes name of the workflowParam and deletes it. Returns an error if one occurs.
func (c *FakeWorkflowParams) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workflowparamsResource, c.ns, name), &v1alpha1.WorkflowParam{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkflowParams) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workflowparamsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkflowParamList{})
	return err
}

// Patch applies the patch and returns the patched workflowParam.
func (c *FakeWorkflowParams) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkflowParam, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workflowparamsResource, c.ns, name, data, subresources...), &v1alpha1.WorkflowParam{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowParam), err
}
