apiVersion: v2
description: A Helm chart for Cyclone
name: cyclone
version: v1.2.0-rc
appVersion: v1.2.0-rc
keywords:
  - cicd
  - workflow
  - devops
  - k8s
sources:
  - https://github.com/caicloud/cyclone
