/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/caicloud/cyclone/pkg/apis/cyclone/v1alpha1"
	scheme "github.com/caicloud/cyclone/pkg/k8s/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CycloneResourcesGetter has a method to return a CycloneResourceInterface.
// A group's client should implement this interface.
type CycloneResourcesGetter interface {
	CycloneResources(namespace string) CycloneResourceInterface
}

// CycloneResourceInterface has methods to work with CycloneResource resources.
type CycloneResourceInterface interface {
	Create(*v1alpha1.CycloneResource) (*v1alpha1.CycloneResource, error)
	Update(*v1alpha1.CycloneResource) (*v1alpha1.CycloneResource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CycloneResource, error)
	List(opts v1.ListOptions) (*v1alpha1.CycloneResourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CycloneResource, err error)
	CycloneResourceExpansion
}

// cycloneResources implements CycloneResourceInterface
type cycloneResources struct {
	client rest.Interface
	ns     string
}

// newCycloneResources returns a CycloneResources
func newCycloneResources(c *CycloneV1alpha1Client, namespace string) *cycloneResources {
	return &cycloneResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cycloneResource, and returns the corresponding cycloneResource object, and an error if there is any.
func (c *cycloneResources) Get(name string, options v1.GetOptions) (result *v1alpha1.CycloneResource, err error) {
	result = &v1alpha1.CycloneResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cycloneresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CycloneResources that match those selectors.
func (c *cycloneResources) List(opts v1.ListOptions) (result *v1alpha1.CycloneResourceList, err error) {
	result = &v1alpha1.CycloneResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cycloneresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cycloneResources.
func (c *cycloneResources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cycloneresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cycloneResource and creates it.  Returns the server's representation of the cycloneResource, and an error, if there is any.
func (c *cycloneResources) Create(cycloneResource *v1alpha1.CycloneResource) (result *v1alpha1.CycloneResource, err error) {
	result = &v1alpha1.CycloneResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cycloneresources").
		Body(cycloneResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cycloneResource and updates it. Returns the server's representation of the cycloneResource, and an error, if there is any.
func (c *cycloneResources) Update(cycloneResource *v1alpha1.CycloneResource) (result *v1alpha1.CycloneResource, err error) {
	result = &v1alpha1.CycloneResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cycloneresources").
		Name(cycloneResource.Name).
		Body(cycloneResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the cycloneResource and deletes it. Returns an error if one occurs.
func (c *cycloneResources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cycloneresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cycloneResources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cycloneresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cycloneResource.
func (c *cycloneResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CycloneResource, err error) {
	result = &v1alpha1.CycloneResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cycloneresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
