/*
Copyright 2019 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ExecutionClusterExpansion interface{}

type ProjectExpansion interface{}

type ResourceExpansion interface{}

type StageExpansion interface{}

type WorkflowExpansion interface{}

type WorkflowRunExpansion interface{}

type WorkflowTriggerExpansion interface{}
