/*
Copyright 2018 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type CycloneResourceExpansion interface{}

type StageExpansion interface{}

type StageTemplateExpansion interface{}

type WorkflowExpansion interface{}

type WorkflowParamExpansion interface{}

type WorkflowRunExpansion interface{}

type WorkflowTriggerExpansion interface{}
