/*
Copyright 2019 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/caicloud/cyclone/pkg/apis/cyclone/v1alpha1"
	scheme "github.com/caicloud/cyclone/pkg/k8s/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StageTemplatesGetter has a method to return a StageTemplateInterface.
// A group's client should implement this interface.
type StageTemplatesGetter interface {
	StageTemplates(namespace string) StageTemplateInterface
}

// StageTemplateInterface has methods to work with StageTemplate resources.
type StageTemplateInterface interface {
	Create(*v1alpha1.StageTemplate) (*v1alpha1.StageTemplate, error)
	Update(*v1alpha1.StageTemplate) (*v1alpha1.StageTemplate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StageTemplate, error)
	List(opts v1.ListOptions) (*v1alpha1.StageTemplateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StageTemplate, err error)
	StageTemplateExpansion
}

// stageTemplates implements StageTemplateInterface
type stageTemplates struct {
	client rest.Interface
	ns     string
}

// newStageTemplates returns a StageTemplates
func newStageTemplates(c *CycloneV1alpha1Client, namespace string) *stageTemplates {
	return &stageTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the stageTemplate, and returns the corresponding stageTemplate object, and an error if there is any.
func (c *stageTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.StageTemplate, err error) {
	result = &v1alpha1.StageTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stagetemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StageTemplates that match those selectors.
func (c *stageTemplates) List(opts v1.ListOptions) (result *v1alpha1.StageTemplateList, err error) {
	result = &v1alpha1.StageTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("stagetemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested stageTemplates.
func (c *stageTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("stagetemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a stageTemplate and creates it.  Returns the server's representation of the stageTemplate, and an error, if there is any.
func (c *stageTemplates) Create(stageTemplate *v1alpha1.StageTemplate) (result *v1alpha1.StageTemplate, err error) {
	result = &v1alpha1.StageTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("stagetemplates").
		Body(stageTemplate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a stageTemplate and updates it. Returns the server's representation of the stageTemplate, and an error, if there is any.
func (c *stageTemplates) Update(stageTemplate *v1alpha1.StageTemplate) (result *v1alpha1.StageTemplate, err error) {
	result = &v1alpha1.StageTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("stagetemplates").
		Name(stageTemplate.Name).
		Body(stageTemplate).
		Do().
		Into(result)
	return
}

// Delete takes name of the stageTemplate and deletes it. Returns an error if one occurs.
func (c *stageTemplates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stagetemplates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *stageTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("stagetemplates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched stageTemplate.
func (c *stageTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StageTemplate, err error) {
	result = &v1alpha1.StageTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("stagetemplates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
