/*
Copyright 2019 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/caicloud/cyclone/pkg/apis/cyclone/v1alpha1"
	scheme "github.com/caicloud/cyclone/pkg/k8s/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WorkflowParamsGetter has a method to return a WorkflowParamInterface.
// A group's client should implement this interface.
type WorkflowParamsGetter interface {
	WorkflowParams(namespace string) WorkflowParamInterface
}

// WorkflowParamInterface has methods to work with WorkflowParam resources.
type WorkflowParamInterface interface {
	Create(*v1alpha1.WorkflowParam) (*v1alpha1.WorkflowParam, error)
	Update(*v1alpha1.WorkflowParam) (*v1alpha1.WorkflowParam, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.WorkflowParam, error)
	List(opts v1.ListOptions) (*v1alpha1.WorkflowParamList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkflowParam, err error)
	WorkflowParamExpansion
}

// workflowParams implements WorkflowParamInterface
type workflowParams struct {
	client rest.Interface
	ns     string
}

// newWorkflowParams returns a WorkflowParams
func newWorkflowParams(c *CycloneV1alpha1Client, namespace string) *workflowParams {
	return &workflowParams{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workflowParam, and returns the corresponding workflowParam object, and an error if there is any.
func (c *workflowParams) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkflowParam, err error) {
	result = &v1alpha1.WorkflowParam{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workflowparams").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkflowParams that match those selectors.
func (c *workflowParams) List(opts v1.ListOptions) (result *v1alpha1.WorkflowParamList, err error) {
	result = &v1alpha1.WorkflowParamList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workflowparams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workflowParams.
func (c *workflowParams) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workflowparams").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a workflowParam and creates it.  Returns the server's representation of the workflowParam, and an error, if there is any.
func (c *workflowParams) Create(workflowParam *v1alpha1.WorkflowParam) (result *v1alpha1.WorkflowParam, err error) {
	result = &v1alpha1.WorkflowParam{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workflowparams").
		Body(workflowParam).
		Do().
		Into(result)
	return
}

// Update takes the representation of a workflowParam and updates it. Returns the server's representation of the workflowParam, and an error, if there is any.
func (c *workflowParams) Update(workflowParam *v1alpha1.WorkflowParam) (result *v1alpha1.WorkflowParam, err error) {
	result = &v1alpha1.WorkflowParam{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workflowparams").
		Name(workflowParam.Name).
		Body(workflowParam).
		Do().
		Into(result)
	return
}

// Delete takes name of the workflowParam and deletes it. Returns an error if one occurs.
func (c *workflowParams) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workflowparams").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workflowParams) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workflowparams").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched workflowParam.
func (c *workflowParams) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkflowParam, err error) {
	result = &v1alpha1.WorkflowParam{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workflowparams").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
