/*
Copyright 2020 caicloud authors. All rights reserved.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/caicloud/cyclone/pkg/k8s/clientset/typed/resource/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCaicloudV1beta1 struct {
	*testing.Fake
}

func (c *FakeCaicloudV1beta1) Clusters() v1beta1.ClusterInterface {
	return &FakeClusters{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCaicloudV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
