/*
Copyright 2019 caicloud authors. All rights reserved.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "k8s.io/client-go/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Resources returns a ResourceInformer.
	Resources() ResourceInformer
	// Stages returns a StageInformer.
	Stages() StageInformer
	// StageTemplates returns a StageTemplateInformer.
	StageTemplates() StageTemplateInformer
	// Workflows returns a WorkflowInformer.
	Workflows() WorkflowInformer
	// WorkflowParams returns a WorkflowParamInformer.
	WorkflowParams() WorkflowParamInformer
	// WorkflowRuns returns a WorkflowRunInformer.
	WorkflowRuns() WorkflowRunInformer
	// WorkflowTriggers returns a WorkflowTriggerInformer.
	WorkflowTriggers() WorkflowTriggerInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Resources returns a ResourceInformer.
func (v *version) Resources() ResourceInformer {
	return &resourceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Stages returns a StageInformer.
func (v *version) Stages() StageInformer {
	return &stageInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// StageTemplates returns a StageTemplateInformer.
func (v *version) StageTemplates() StageTemplateInformer {
	return &stageTemplateInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Workflows returns a WorkflowInformer.
func (v *version) Workflows() WorkflowInformer {
	return &workflowInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkflowParams returns a WorkflowParamInformer.
func (v *version) WorkflowParams() WorkflowParamInformer {
	return &workflowParamInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkflowRuns returns a WorkflowRunInformer.
func (v *version) WorkflowRuns() WorkflowRunInformer {
	return &workflowRunInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WorkflowTriggers returns a WorkflowTriggerInformer.
func (v *version) WorkflowTriggers() WorkflowTriggerInformer {
	return &workflowTriggerInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
